package com.neobank.reconciliation.domain;

public enum DiscrepancyType {
    ACCOUNT_LEDGER_BALANCE_MISMATCH,
    COMPLETED_TRANSFER_WITHOUT_LEDGER,
    LEDGER_WITHOUT_VALID_TRANSFER,
    REVERSAL_LINK_INCONSISTENCY,
    DUPLICATE_REVERSAL,
    REVERSAL_WITHOUT_LEDGER
}

